
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 13 2026 07:25:46 EDT (Mar 13 2026 11:25:46 UTC)

// Verification Directory fv/carry_save_adder_16bit 

module full_adder(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFX1 g85__2398(.A (a), .B (cin), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_45(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g92(.A (b), .B (a), .CI (cin), .CO (cout), .S (sum));
endmodule

module full_adder_44(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFX1 g92(.A (b), .B (a), .CI (cin), .CO (cout), .S (sum));
endmodule

module full_adder_43(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__2802(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_42(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__1705(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_41(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__5122(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_40(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__8246(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_39(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__7098(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_38(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__6131(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_37(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__1881(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_36(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__5115(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_35(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__7482(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_34(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__4733(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_33(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__6161(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_32(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__9315(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module full_adder_31(a, b, cin, sum, cout);
  input a, b, cin;
  output sum, cout;
  wire a, b, cin;
  wire sum, cout;
  ADDFXL g85__9945(.A (cin), .B (a), .CI (b), .CO (cout), .S (sum));
endmodule

module carry_save_adder_16bit(a, b, c, final_sum);
  input [15:0] a, b, c;
  output [17:0] final_sum;
  wire [15:0] a, b, c;
  wire [17:0] final_sum;
  wire [15:0] save_carry;
  wire [15:0] save_sum;
  wire add_47_42_n_0, add_47_42_n_1, add_47_42_n_2, add_47_42_n_3,
       add_47_42_n_4, add_47_42_n_5, add_47_42_n_6, add_47_42_n_7;
  wire add_47_42_n_8, add_47_42_n_9, add_47_42_n_10, add_47_42_n_11,
       add_47_42_n_12, add_47_42_n_13, add_47_42_n_14, add_47_42_n_15;
  wire add_47_42_n_16, add_47_42_n_17, add_47_42_n_18, add_47_42_n_19,
       add_47_42_n_20, add_47_42_n_21, add_47_42_n_22, add_47_42_n_23;
  wire add_47_42_n_24, add_47_42_n_25, add_47_42_n_26, add_47_42_n_27,
       add_47_42_n_29, add_47_42_n_30, add_47_42_n_31, add_47_42_n_32;
  wire add_47_42_n_33, add_47_42_n_34, add_47_42_n_35, add_47_42_n_37,
       add_47_42_n_38, add_47_42_n_39, add_47_42_n_40, add_47_42_n_41;
  wire add_47_42_n_42, add_47_42_n_44, add_47_42_n_45, add_47_42_n_47,
       add_47_42_n_48, add_47_42_n_49, add_47_42_n_51, add_47_42_n_52;
  wire add_47_42_n_53, add_47_42_n_55, add_47_42_n_58, add_47_42_n_59,
       add_47_42_n_60, add_47_42_n_62, add_47_42_n_63, add_47_42_n_64;
  wire add_47_42_n_66, add_47_42_n_68, add_47_42_n_69, add_47_42_n_70,
       add_47_42_n_72, add_47_42_n_73, add_47_42_n_74, add_47_42_n_76;
  wire add_47_42_n_77, add_47_42_n_78, add_47_42_n_79, add_47_42_n_80,
       add_47_42_n_84, add_47_42_n_85, add_47_42_n_87, n_121;
  full_adder \csa_stage[0].fa (.a (a[0]), .b (b[0]), .cin (c[0]), .sum
       (final_sum[0]), .cout (save_carry[0]));
  full_adder_45 \csa_stage[1].fa (.a (a[1]), .b (b[1]), .cin (c[1]),
       .sum (save_sum[1]), .cout (save_carry[1]));
  full_adder_44 \csa_stage[2].fa (.a (a[2]), .b (b[2]), .cin (c[2]),
       .sum (save_sum[2]), .cout (save_carry[2]));
  full_adder_43 \csa_stage[3].fa (.a (a[3]), .b (b[3]), .cin (c[3]),
       .sum (save_sum[3]), .cout (save_carry[3]));
  full_adder_42 \csa_stage[4].fa (.a (a[4]), .b (b[4]), .cin (c[4]),
       .sum (save_sum[4]), .cout (save_carry[4]));
  full_adder_41 \csa_stage[5].fa (.a (a[5]), .b (b[5]), .cin (c[5]),
       .sum (save_sum[5]), .cout (save_carry[5]));
  full_adder_40 \csa_stage[6].fa (.a (a[6]), .b (b[6]), .cin (c[6]),
       .sum (save_sum[6]), .cout (save_carry[6]));
  full_adder_39 \csa_stage[7].fa (.a (a[7]), .b (b[7]), .cin (c[7]),
       .sum (save_sum[7]), .cout (save_carry[7]));
  full_adder_38 \csa_stage[8].fa (.a (a[8]), .b (b[8]), .cin (c[8]),
       .sum (save_sum[8]), .cout (save_carry[8]));
  full_adder_37 \csa_stage[9].fa (.a (a[9]), .b (b[9]), .cin (c[9]),
       .sum (save_sum[9]), .cout (save_carry[9]));
  full_adder_36 \csa_stage[10].fa (.a (a[10]), .b (b[10]), .cin
       (c[10]), .sum (save_sum[10]), .cout (save_carry[10]));
  full_adder_35 \csa_stage[11].fa (.a (a[11]), .b (b[11]), .cin
       (c[11]), .sum (save_sum[11]), .cout (save_carry[11]));
  full_adder_34 \csa_stage[12].fa (.a (a[12]), .b (b[12]), .cin
       (c[12]), .sum (save_sum[12]), .cout (save_carry[12]));
  full_adder_33 \csa_stage[13].fa (.a (a[13]), .b (b[13]), .cin
       (c[13]), .sum (save_sum[13]), .cout (save_carry[13]));
  full_adder_32 \csa_stage[14].fa (.a (a[14]), .b (b[14]), .cin
       (c[14]), .sum (save_sum[14]), .cout (save_carry[14]));
  full_adder_31 \csa_stage[15].fa (.a (a[15]), .b (b[15]), .cin
       (c[15]), .sum (save_sum[15]), .cout (save_carry[15]));
  ADDHX2 add_47_42_g565__2883(.A (save_carry[15]), .B (add_47_42_n_87),
       .CO (final_sum[17]), .S (final_sum[16]));
  OAI2BB1X1 add_47_42_g566__2346(.A0N (add_47_42_n_12), .A1N
       (add_47_42_n_85), .B0 (add_47_42_n_26), .Y (add_47_42_n_87));
  CLKXOR2X2 add_47_42_g567__1666(.A (add_47_42_n_35), .B
       (add_47_42_n_84), .Y (final_sum[15]));
  OAI21X1 add_47_42_g568__7410(.A0 (add_47_42_n_18), .A1
       (add_47_42_n_78), .B0 (add_47_42_n_5), .Y (add_47_42_n_85));
  OAI21X1 add_47_42_g569__6417(.A0 (add_47_42_n_18), .A1
       (add_47_42_n_80), .B0 (add_47_42_n_5), .Y (add_47_42_n_84));
  OAI21X1 add_47_42_g572__5107(.A0 (add_47_42_n_40), .A1
       (add_47_42_n_76), .B0 (add_47_42_n_79), .Y (final_sum[13]));
  NOR2XL add_47_42_g573__6260(.A (add_47_42_n_41), .B (add_47_42_n_77),
       .Y (add_47_42_n_80));
  NAND2XL add_47_42_g574__4319(.A (add_47_42_n_40), .B
       (add_47_42_n_76), .Y (add_47_42_n_79));
  NOR2XL add_47_42_g575__8428(.A (add_47_42_n_41), .B (add_47_42_n_77),
       .Y (add_47_42_n_78));
  NOR2XL add_47_42_g576__5526(.A (add_47_42_n_14), .B (add_47_42_n_74),
       .Y (add_47_42_n_77));
  NAND2XL add_47_42_g577__6783(.A (add_47_42_n_6), .B (add_47_42_n_74),
       .Y (add_47_42_n_76));
  OAI21X1 add_47_42_g578__3680(.A0 (add_47_42_n_30), .A1
       (add_47_42_n_72), .B0 (add_47_42_n_73), .Y (final_sum[12]));
  NAND2BX1 add_47_42_g579__1617(.AN (add_47_42_n_22), .B
       (add_47_42_n_72), .Y (add_47_42_n_74));
  NAND2XL add_47_42_g580__2802(.A (add_47_42_n_30), .B
       (add_47_42_n_72), .Y (add_47_42_n_73));
  OAI21X1 add_47_42_g581__1705(.A0 (add_47_42_n_9), .A1
       (add_47_42_n_69), .B0 (add_47_42_n_23), .Y (add_47_42_n_72));
  OAI21X1 add_47_42_g582__5122(.A0 (add_47_42_n_29), .A1
       (add_47_42_n_68), .B0 (add_47_42_n_70), .Y (final_sum[11]));
  NAND2XL add_47_42_g583__8246(.A (add_47_42_n_29), .B
       (add_47_42_n_68), .Y (add_47_42_n_70));
  AOI21X1 add_47_42_g584__7098(.A0 (add_47_42_n_15), .A1
       (add_47_42_n_63), .B0 (add_47_42_n_2), .Y (add_47_42_n_69));
  OAI2BB1X1 add_47_42_g585__6131(.A0N (add_47_42_n_15), .A1N
       (add_47_42_n_63), .B0 (add_47_42_n_3), .Y (add_47_42_n_68));
  OAI21X1 add_47_42_g586__1881(.A0 (add_47_42_n_32), .A1
       (add_47_42_n_63), .B0 (add_47_42_n_66), .Y (final_sum[10]));
  NAND2XL add_47_42_g587__5115(.A (add_47_42_n_32), .B
       (add_47_42_n_63), .Y (add_47_42_n_66));
  OAI21X1 add_47_42_g588__7482(.A0 (add_47_42_n_33), .A1
       (add_47_42_n_62), .B0 (add_47_42_n_64), .Y (final_sum[9]));
  NAND2XL add_47_42_g589__4733(.A (add_47_42_n_33), .B
       (add_47_42_n_62), .Y (add_47_42_n_64));
  OAI221X1 add_47_42_g590__6161(.A0 (add_47_42_n_7), .A1
       (add_47_42_n_59), .B0 (add_47_42_n_7), .B1 (add_47_42_n_1), .C0
       (add_47_42_n_11), .Y (add_47_42_n_63));
  NAND2XL add_47_42_g591__9315(.A (add_47_42_n_1), .B (add_47_42_n_59),
       .Y (add_47_42_n_62));
  OAI21X1 add_47_42_g592__9945(.A0 (add_47_42_n_31), .A1
       (add_47_42_n_58), .B0 (add_47_42_n_60), .Y (final_sum[8]));
  NAND2XL add_47_42_g593__2883(.A (add_47_42_n_31), .B
       (add_47_42_n_58), .Y (add_47_42_n_60));
  NAND2BX1 add_47_42_g594__2346(.AN (add_47_42_n_10), .B
       (add_47_42_n_58), .Y (add_47_42_n_59));
  ADDFX1 add_47_42_g595__1666(.A (save_sum[7]), .B (save_carry[6]), .CI
       (add_47_42_n_55), .CO (add_47_42_n_58), .S (final_sum[7]));
  ADDFX1 add_47_42_g596__7410(.A (save_sum[6]), .B (save_carry[5]), .CI
       (add_47_42_n_51), .CO (add_47_42_n_55), .S (final_sum[6]));
  OAI21X1 add_47_42_g597__6417(.A0 (add_47_42_n_39), .A1
       (add_47_42_n_52), .B0 (add_47_42_n_53), .Y (final_sum[5]));
  NAND2XL add_47_42_g598__5477(.A (add_47_42_n_39), .B
       (add_47_42_n_52), .Y (add_47_42_n_53));
  OAI2BB1X1 add_47_42_g599__2398(.A0N (add_47_42_n_17), .A1N
       (add_47_42_n_47), .B0 (add_47_42_n_4), .Y (add_47_42_n_52));
  OAI211X1 add_47_42_g600__5107(.A0 (add_47_42_n_4), .A1
       (add_47_42_n_8), .B0 (add_47_42_n_25), .C0 (add_47_42_n_48), .Y
       (add_47_42_n_51));
  OAI21X1 add_47_42_g601__6260(.A0 (add_47_42_n_37), .A1
       (add_47_42_n_47), .B0 (add_47_42_n_49), .Y (final_sum[4]));
  NAND2XL add_47_42_g602__4319(.A (add_47_42_n_37), .B
       (add_47_42_n_47), .Y (add_47_42_n_49));
  NAND2XL add_47_42_g603__8428(.A (add_47_42_n_27), .B
       (add_47_42_n_47), .Y (add_47_42_n_48));
  OAI21X1 add_47_42_g604__5526(.A0 (add_47_42_n_13), .A1
       (add_47_42_n_45), .B0 (add_47_42_n_19), .Y (add_47_42_n_47));
  MX2X1 add_47_42_g605__6783(.A (add_47_42_n_45), .B (add_47_42_n_44),
       .S0 (add_47_42_n_34), .Y (final_sum[3]));
  CLKINVX1 add_47_42_g606(.A (add_47_42_n_44), .Y (add_47_42_n_45));
  OAI21X1 add_47_42_g607__3680(.A0 (add_47_42_n_21), .A1
       (add_47_42_n_0), .B0 (add_47_42_n_20), .Y (add_47_42_n_44));
  OAI21X1 add_47_42_g608__1617(.A0 (add_47_42_n_0), .A1
       (add_47_42_n_38), .B0 (add_47_42_n_42), .Y (final_sum[2]));
  NAND2XL add_47_42_g609__2802(.A (add_47_42_n_0), .B (add_47_42_n_38),
       .Y (add_47_42_n_42));
  OAI21X1 add_47_42_g610__1705(.A0 (add_47_42_n_14), .A1
       (add_47_42_n_6), .B0 (add_47_42_n_24), .Y (add_47_42_n_41));
  NAND2BX1 add_47_42_g611__5122(.AN (add_47_42_n_14), .B
       (add_47_42_n_24), .Y (add_47_42_n_40));
  NAND2BX1 add_47_42_g612__8246(.AN (add_47_42_n_8), .B
       (add_47_42_n_25), .Y (add_47_42_n_39));
  NOR2BX1 add_47_42_g613__7098(.AN (add_47_42_n_20), .B
       (add_47_42_n_21), .Y (add_47_42_n_38));
  AND2XL add_47_42_g614__6131(.A (add_47_42_n_26), .B (add_47_42_n_12),
       .Y (add_47_42_n_35));
  NAND2XL add_47_42_g615__1881(.A (add_47_42_n_4), .B (add_47_42_n_17),
       .Y (add_47_42_n_37));
  NAND2BX1 add_47_42_g617__7482(.AN (add_47_42_n_13), .B
       (add_47_42_n_19), .Y (add_47_42_n_34));
  OA21X1 add_47_42_g618__4733(.A0 (save_carry[0]), .A1 (save_sum[1]),
       .B0 (add_47_42_n_0), .Y (final_sum[1]));
  NOR2XL add_47_42_g619__6161(.A (add_47_42_n_16), .B (add_47_42_n_8),
       .Y (add_47_42_n_27));
  NAND2BX1 add_47_42_g620__9315(.AN (add_47_42_n_7), .B
       (add_47_42_n_11), .Y (add_47_42_n_33));
  NAND2XL add_47_42_g621__9945(.A (add_47_42_n_3), .B (add_47_42_n_15),
       .Y (add_47_42_n_32));
  NAND2BX1 add_47_42_g622__2883(.AN (add_47_42_n_10), .B
       (add_47_42_n_1), .Y (add_47_42_n_31));
  NAND2BX1 add_47_42_g623__2346(.AN (add_47_42_n_22), .B
       (add_47_42_n_6), .Y (add_47_42_n_30));
  NAND2BX1 add_47_42_g624__1666(.AN (add_47_42_n_9), .B
       (add_47_42_n_23), .Y (add_47_42_n_29));
  CLKINVX1 add_47_42_g625(.A (add_47_42_n_16), .Y (add_47_42_n_17));
  NAND2XL add_47_42_g626__7410(.A (save_carry[14]), .B (save_sum[15]),
       .Y (add_47_42_n_26));
  NAND2XL add_47_42_g627__6417(.A (save_carry[4]), .B (save_sum[5]), .Y
       (add_47_42_n_25));
  NAND2XL add_47_42_g628__5477(.A (save_carry[12]), .B (save_sum[13]),
       .Y (add_47_42_n_24));
  NAND2XL add_47_42_g629__2398(.A (save_carry[10]), .B (save_sum[11]),
       .Y (add_47_42_n_23));
  NOR2XL add_47_42_g630__5107(.A (save_carry[11]), .B (save_sum[12]),
       .Y (add_47_42_n_22));
  NOR2XL add_47_42_g631__6260(.A (save_carry[1]), .B (save_sum[2]), .Y
       (add_47_42_n_21));
  NAND2XL add_47_42_g632__4319(.A (save_carry[1]), .B (save_sum[2]), .Y
       (add_47_42_n_20));
  NAND2XL add_47_42_g633__8428(.A (save_carry[2]), .B (save_sum[3]), .Y
       (add_47_42_n_19));
  NOR2XL add_47_42_g634__5526(.A (save_carry[13]), .B (save_sum[14]),
       .Y (add_47_42_n_18));
  NOR2XL add_47_42_g635__6783(.A (save_carry[3]), .B (save_sum[4]), .Y
       (add_47_42_n_16));
  OR2X1 add_47_42_g636__3680(.A (save_carry[9]), .B (save_sum[10]), .Y
       (add_47_42_n_15));
  NOR2XL add_47_42_g637__1617(.A (save_carry[12]), .B (save_sum[13]),
       .Y (add_47_42_n_14));
  INVXL add_47_42_g638(.A (add_47_42_n_3), .Y (add_47_42_n_2));
  NOR2XL add_47_42_g639__2802(.A (save_carry[2]), .B (save_sum[3]), .Y
       (add_47_42_n_13));
  OR2XL add_47_42_g640__1705(.A (save_carry[14]), .B (save_sum[15]), .Y
       (add_47_42_n_12));
  NAND2XL add_47_42_g641__5122(.A (save_carry[8]), .B (save_sum[9]), .Y
       (add_47_42_n_11));
  NOR2XL add_47_42_g642__8246(.A (save_carry[7]), .B (save_sum[8]), .Y
       (add_47_42_n_10));
  NOR2XL add_47_42_g643__7098(.A (save_carry[10]), .B (save_sum[11]),
       .Y (add_47_42_n_9));
  NOR2XL add_47_42_g644__6131(.A (save_carry[4]), .B (save_sum[5]), .Y
       (add_47_42_n_8));
  NOR2XL add_47_42_g645__1881(.A (save_carry[8]), .B (save_sum[9]), .Y
       (add_47_42_n_7));
  NAND2XL add_47_42_g646__5115(.A (save_carry[11]), .B (save_sum[12]),
       .Y (add_47_42_n_6));
  NAND2XL add_47_42_g647__7482(.A (save_carry[13]), .B (save_sum[14]),
       .Y (add_47_42_n_5));
  NAND2XL add_47_42_g648__4733(.A (save_carry[3]), .B (save_sum[4]), .Y
       (add_47_42_n_4));
  NAND2XL add_47_42_g649__6161(.A (save_carry[9]), .B (save_sum[10]),
       .Y (add_47_42_n_3));
  NAND2XL add_47_42_g650__9315(.A (save_carry[7]), .B (save_sum[8]), .Y
       (add_47_42_n_1));
  NAND2X1 add_47_42_g651__9945(.A (save_carry[0]), .B (save_sum[1]), .Y
       (add_47_42_n_0));
  XNOR2X1 g2(.A (n_121), .B (add_47_42_n_80), .Y (final_sum[14]));
  NOR2BXL g3(.AN (add_47_42_n_5), .B (add_47_42_n_18), .Y (n_121));
endmodule

